### ISSUE TITLE
Create task - Sanjay

### ISSUE THREAD

**Issue by deimie** [SimonBrunzell/flask_portfolio#41]

**Comment by SanjayB06** [comment]
### Program Idea
A tool that will recommend future courses to the user in order to 
- Meet graduation requirements
- Meet UC Requirements
- Maximize GPA
### Specifications
#### User input
User will input their current grade in school. After which they will input all the courses they have taken or will take up to the end of the school year. Potential future improvement includes taking the GPA until that point into consideration.
#### Data
The program will have a database of courses, mostly in DNHS, and the requirement that they will count towards. It might also include a measure of their difficulty. It will include any prerequisites as well as an average grade level. 
#### Algorithm
The program will use the courses the user has already taken to eliminate them from the potential future courses. It will also determine how far the user is towards meeting each of the requirements. Then, it will analyze how much time is left in school. If it turns out the requirements can not be met, it will let the user know. In the likely scenario that the requirements can be met, it will iteratively move through the various requirements and layout the courses that best match the users previous course history and grade.  
#### Output
The program will output all the courses that the user should take in the remaining years of high school. It will also include a chart of the requirements that have been met and will be met based on the output.
